#!/usr/bin/python3

"""Getting a shell in the target environment with all the correct behavior in
place, correct across all series, backends, and virtualizations has some
pitfalls.  Test for the known challenges in getting all this correct."""

import os
import unittest
import subprocess


class Tests(unittest.TestCase):
    def test_pts_stat(self):
        # some methods of creating the shell as user result in incorrect
        # ownership of the pseudo terminal.
        tty = subprocess.check_output("tty").decode().strip()
        stat = os.stat(tty)
        self.assertEqual(os.getuid(), stat.st_uid, f"{tty} uid")

    def test_has_home(self):
        self.assertTrue(os.environ["HOME"])


if __name__ == "__main__":
    unittest.main()
